Repository EveryUniv/student-council-homepage-frontend, pull requests merged in 2023-04, with the labels that each got.

#245 Refactor/233
  src/App.tsx
  src/AuthRoute.tsx
  src/Router.tsx
  src/atoms/LoginState.tsx
  src/atoms/UserInfo.tsx
  src/components/nav/Gnb.tsx
  src/components/nav/MobileMenu.tsx
  src/components/nav/UserMenu.tsx
  src/hooks/UseLogin.tsx
  src/hooks/UseLogout.tsx
  src/hooks/UseMyInfo.tsx
  src/index.tsx
  src/pages/Admin.tsx
  src/pages/Login.tsx
  src/pages/communication/petition/components/Editor.tsx
  src/pages/communication/petition/components/FilterControl.tsx
  src/pages/communication/petition/components/PetitionChart.tsx
  src/pages/communication/petition/components/Post.tsx
  src/pages/communication/petition/functions/GetCategories.tsx
  src/pages/communication/suggestion/SuggestionEditor.tsx
  src/pages/communication/suggestion/components/FilterControl.tsx
  src/pages/communication/suggestion/components/post/Post.tsx
  src/pages/communication/suggestion/functions/GetCategories.tsx
  src/pages/conference/components/ConferenceBoard.tsx
  src/pages/conference/components/ConferenceEditor.tsx
  src/pages/council/news/components/NewsBoard.tsx
  src/pages/council/news/components/NewsEditor.tsx
  src/pages/council/news/components/mobile/NewsBoard.tsx
  src/pages/council/news/components/post/Desktop.tsx
  src/pages/council/news/components/post/Mobile.tsx
  src/pages/event/Event.tsx
  src/pages/event/components/Banner.tsx
  src/pages/event/components/CheckIcon.tsx
  src/pages/event/components/CloseIcon.tsx
  src/pages/event/components/Modal.tsx
  src/pages/event/components/VoteContainer.tsx
  src/pages/event/data/index.ts
  src/pages/event/images/KDK.png
  src/pages/event/images/banner.png
  src/pages/event/images/곰지락곰지락.png
  src/pages/event/images/단곰지니.png
  src/pages/event/images/옷잘알.png
  src/pages/event/images/인생최후끌어치기.png
  src/pages/event/images/팀원없조.png
  src/pages/rental/RentalNew.tsx
  src/pages/rules/components/RuleEditor.tsx
  src/pages/rules/components/RulesBoard.tsx
  src/pages/rules/components/mobile/RulesBoard.tsx
  src/pages/rules/components/post/Desktop.tsx
  src/pages/rules/components/post/Mobile.tsx
  src/types/user.d.ts
Labels: refactor

#253 feat/200 게시글 태그 기능
  src/pages/communication/petition/components/Editor.tsx
  src/pages/communication/petition/components/Post.tsx
  src/pages/communication/suggestion/SuggestionEditor.tsx
  src/pages/communication/suggestion/components/post/Post.tsx
  src/pages/communication/suggestion/components/post/PostProps.ts
Labels: feature

#276 [DOCS] PR 템플릿 추가
  .github/pull_request_template.md
Labels: docs

#277 fix: 권한 문제 해결
  src/pages/council/news/components/post/Desktop.tsx
Labels: bug, chore, api
